stf:
  image: cocoon/droyd-stf
  ports:
    - "7100:7100"
    - "7110:7110"
    - "7400:7400"
    - "7401:7401"
    - "7402:7402"
    - "7403:7403"
    - "7404:7404"
    - "7405:7405"
    - "7406:7406"
    - "7407:7407"
    - "5000:5000"
    - "8080:8080" 
  privileged: true
  environment:
    - PYTHONIOENCODING="utf-8"

nginx:
  image: nginx
  links:
   - stf
  volumes:
    - ./site/html:/usr/share/nginx/html
    - ./site/nginx/nginx.conf:/etc/nginx/nginx.conf
    #- "./site/default.template:/etc/nginx/conf.d/default.template"
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.99.100
    - NGINX_PORT=80
  #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"



  #/etc/nginx/conf.d/default.conf
  # 