stf:
  image: cocoon/droyd-stf
  ports:
    - "7100:7100"
    - "5000:5000"
    - "8080:8080" 
  privileged: true
  environment:
    - PYTHONIOENCODING="utf-8"

nginx:
  image: nginx
  links:
   - stf
  volumes:
    - ./site/html:/usr/share/nginx/html
    - ./site/default.conf:/etc/nginx/conf.d/default.conf
    #- "./site/default.template:/etc/nginx/conf.d/default.template"
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.99.101
    - NGINX_PORT=80
  #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"



  #/etc/nginx/conf.d/default.conf
  # 