data:
  build: ./data
stf:
  image: cocoon/droyd-stf
  ports:
    - "5000:5000"
    - "8080:8080" 
    - "7100:7100"
    - "7110:7110"
    - "7400:7400"
    - "7401:7401"
    - "7402:7402"
    - "7403:7403"
    - "7404:7404"
    - "7405:7405"
    - "7406:7406"
    - "7407:7407"
  privileged: true
  environment:
    - NGINX_HOST=192.168.99.100
    - PYTHONIOENCODING="utf-8"

  command: '/bin/bash -c "envsubst < /data/templates/Procfile > /data/Procfile; honcho start"'

nginx:
  image: nginx
  links:
   - stf
  volumes:
    - ./site/html:/usr/share/nginx/html
    - ./site/nginx/nginx.conf:/etc/nginx/nginx.conf

  ports:
    - "80:80"
  command: nginx -g 'daemon off;'
